services:
  caddy:
    image: caddy:2.10
    container_name: snisite
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./html:/var/www/html
      - ./logs:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    network_mode: host
    ports:
      - ${SNI_PORT}:${SNI_PORT}
      - 80:80
    restart: 
      unless-stopped

volumes:
  caddy_data:
  caddy_config: